/**
 * HistoryStore tests — Sub-AC 2a: load_history cursor-pagination.
 *
 * Verifies that the HistoryStore correctly:
 *   (a) Stores ciphertext MessageEnvelope blobs in insertion order.
 *   (b) Returns all stored blobs in insertion order across successive pages
 *       with zero gaps.
 *   (c) Advances the cursor correctly so each page picks up exactly where
 *       the previous page left off.
 *   (d) Returns `nextCursor = null` when the store is exhausted.
 *   (e) Handles edge cases: empty store, non-positive limit, stale cursor,
 *       exact-multiple page sizes, single-item pages, cross-conversation
 *       isolation.
 *
 * Encryption is intentionally STUBBED — ciphertext blobs are opaque byte
 * sequences generated by `makeOpaqueBlob()`. The store holds and returns
 * them as-is; it never inspects or decrypts content. This decouples the
 * pagination logic under test from the crypto layer (which is tested
 * separately in e2e-crypto.test.ts and e2e-envelope.test.ts).
 */

import { describe, it, expect } from "vitest";
import { HistoryStore } from "./history-store.js";
import type { ConversationId, HistoryPage } from "./history-store.js";
import type { MessageEnvelope } from "./e2e-envelope.js";

// ---------------------------------------------------------------------------
// Opaque blob factory — encryption stubbed/opaque for pagination tests
//
// Produces a structurally valid `MessageEnvelope` whose `content` block
// contains fake (non-decryptable) base64url strings. The store treats these
// identically to real encrypted envelopes — it never peeks inside `content`.
// ---------------------------------------------------------------------------

/**
 * Build a structurally valid `MessageEnvelope` with opaque (fake) ciphertext.
 * The `content.ciphertext` field encodes the `messageId` in base64 so that
 * each blob is uniquely identifiable in test assertions without decryption.
 */
function makeOpaqueEnvelope(
  conv: ConversationId,
  messageId: string,
  ts: number = 1_718_000_000_000 + parseInt(messageId.replace(/\D/g, "0"), 10),
): MessageEnvelope {
  // Encode messageId as the "ciphertext" so test assertions can identify blobs.
  const opaqueContent = Buffer.from(messageId, "utf8").toString("base64url");
  return {
    v: 1,
    accountId: conv.accountId,
    tenant: conv.tenant,
    sub: conv.sub,
    messageId,
    envelopeType: "conversation",
    ts,
    content: {
      // Fake nonce (12 bytes → 16 base64url chars), unique per envelope.
      nonce: Buffer.from(messageId.padEnd(12, "\0").slice(0, 12)).toString("base64url"),
      // Fake ciphertext — encodes the messageId for test identification.
      ciphertext: opaqueContent,
      // Fake auth tag (16 bytes of zeros as base64url).
      tag: Buffer.alloc(16, 0).toString("base64url"),
    },
  } as MessageEnvelope;
}

/**
 * Build a sequence of M opaque envelopes for the given conversation.
 * Message IDs are: "msg-1", "msg-2", ..., "msg-M".
 * Timestamps increase monotonically: BASE_TS + i * 1000.
 */
function makeEnvelopes(conv: ConversationId, count: number, baseTs = 1_718_000_000_000): MessageEnvelope[] {
  return Array.from({ length: count }, (_, i) => {
    const n = i + 1;
    return makeOpaqueEnvelope(conv, `msg-${n}`, baseTs + n * 1000);
  });
}

/**
 * Drain a HistoryStore by calling loadHistory in a loop until exhausted.
 * Returns all envelopes in the order they were returned across pages.
 */
function drainStore(
  store: HistoryStore,
  conv: ConversationId,
  pageSize: number,
): { allEnvelopes: MessageEnvelope[]; pageCount: number } {
  const allEnvelopes: MessageEnvelope[] = [];
  let cursor: string | null = null;
  let pageCount = 0;

  for (;;) {
    const page: HistoryPage = store.loadHistory(conv, cursor, pageSize);
    allEnvelopes.push(...page.envelopes);
    pageCount++;

    if (page.nextCursor === null) break;
    cursor = page.nextCursor;
  }

  return { allEnvelopes, pageCount };
}

// ---------------------------------------------------------------------------
// Test fixtures
// ---------------------------------------------------------------------------

const CONV: ConversationId = { accountId: "agent1", tenant: "tenant1", sub: "user42" };
const CONV_B: ConversationId = { accountId: "agent1", tenant: "tenant1", sub: "user99" };
const CONV_C: ConversationId = { accountId: "agent2", tenant: "tenant1", sub: "user42" };

// ---------------------------------------------------------------------------
// Suite 1: Core cursor-pagination invariant (Sub-AC 2a primary assertion)
// ---------------------------------------------------------------------------

describe("HistoryStore — load_history cursor-pagination (Sub-AC 2a)", () => {

  // ── Test 1: M=7 blobs, pageSize=3 — canonical successive-pages test ────────

  it(
    "pre-populates M=7 blobs and retrieves all in insertion order across successive pages with zero gaps",
    () => {
      const M = 7;
      const PAGE_SIZE = 3;
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, M);

      // Pre-populate M blobs in insertion order.
      for (const env of envelopes) store.append(CONV, env);
      expect(store.size(CONV)).toBe(M);

      // Drain all pages.
      const { allEnvelopes, pageCount } = drainStore(store, CONV, PAGE_SIZE);

      // (b) Zero gaps — every blob is returned exactly once.
      expect(allEnvelopes).toHaveLength(M);

      // (b) Insertion order preserved — each returned blob matches the original.
      for (let i = 0; i < M; i++) {
        expect(allEnvelopes[i]!.messageId, `blob ${i + 1}: messageId`).toBe(envelopes[i]!.messageId);
        expect(allEnvelopes[i]!.ts, `blob ${i + 1}: ts`).toBe(envelopes[i]!.ts);
        // Ciphertext blob identity preserved (store never mutates content).
        expect(allEnvelopes[i]!.content.ciphertext, `blob ${i + 1}: ciphertext opaque`).toBe(
          envelopes[i]!.content.ciphertext,
        );
      }

      // (c) Correct page count: ceil(M / PAGE_SIZE) = ceil(7/3) = 3 pages.
      expect(pageCount).toBe(Math.ceil(M / PAGE_SIZE));
    },
  );

  // ── Test 2: Cursor advancement — each cursor points to the next page ────────

  it(
    "cursor advancement: nextCursor from page N positions correctly at the start of page N+1",
    () => {
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, 9);
      for (const env of envelopes) store.append(CONV, env);

      // Page 1 (cursor=null → first 3 items: msg-1, msg-2, msg-3)
      const page1 = store.loadHistory(CONV, null, 3);
      expect(page1.envelopes.map((e) => e.messageId)).toEqual(["msg-1", "msg-2", "msg-3"]);
      expect(page1.nextCursor).toBe("msg-3");

      // Page 2 (cursor=msg-3 → next 3: msg-4, msg-5, msg-6)
      const page2 = store.loadHistory(CONV, page1.nextCursor, 3);
      expect(page2.envelopes.map((e) => e.messageId)).toEqual(["msg-4", "msg-5", "msg-6"]);
      expect(page2.nextCursor).toBe("msg-6");

      // Page 3 (cursor=msg-6 → last 3: msg-7, msg-8, msg-9)
      const page3 = store.loadHistory(CONV, page2.nextCursor, 3);
      expect(page3.envelopes.map((e) => e.messageId)).toEqual(["msg-7", "msg-8", "msg-9"]);
      // Store exhausted — no further pages.
      expect(page3.nextCursor).toBeNull();

      // Verify exhaustion: calling with the messageId of the last item returns empty.
      // (nextCursor=null is the termination signal; the last item's messageId is the
      //  exhaustion cursor — pointing past the final element returns empty.)
      const lastId = page3.envelopes[page3.envelopes.length - 1]!.messageId;
      const page4 = store.loadHistory(CONV, lastId, 3);
      expect(page4.envelopes).toHaveLength(0);
      expect(page4.nextCursor).toBeNull();
    },
  );

  // ── Test 3: Large M with small page size ─────────────────────────────────

  it(
    "M=20 blobs with pageSize=4: all 20 returned in insertion order across 5 pages",
    () => {
      const M = 20;
      const PAGE_SIZE = 4;
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, M);
      for (const env of envelopes) store.append(CONV, env);

      const { allEnvelopes, pageCount } = drainStore(store, CONV, PAGE_SIZE);

      expect(allEnvelopes).toHaveLength(M);
      expect(pageCount).toBe(M / PAGE_SIZE); // exactly 5 full pages

      for (let i = 0; i < M; i++) {
        expect(allEnvelopes[i]!.messageId).toBe(`msg-${i + 1}`);
      }
    },
  );

  // ── Test 4: Exact-multiple — M is exactly divisible by pageSize ───────────

  it(
    "M=6 blobs with pageSize=3: returns 2 exact-full pages, nextCursor null on second page",
    () => {
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, 6);
      for (const env of envelopes) store.append(CONV, env);

      const page1 = store.loadHistory(CONV, null, 3);
      expect(page1.envelopes.map((e) => e.messageId)).toEqual(["msg-1", "msg-2", "msg-3"]);
      expect(page1.nextCursor).toBe("msg-3");

      const page2 = store.loadHistory(CONV, page1.nextCursor, 3);
      expect(page2.envelopes.map((e) => e.messageId)).toEqual(["msg-4", "msg-5", "msg-6"]);
      // Last page: store exactly exhausted — nextCursor must be null.
      expect(page2.nextCursor).toBeNull();
    },
  );

  // ── Test 5: Single-item pages (pageSize=1) ────────────────────────────────

  it(
    "pageSize=1: each page returns exactly one blob; N pages for N blobs",
    () => {
      const M = 5;
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, M);
      for (const env of envelopes) store.append(CONV, env);

      const pages: MessageEnvelope[][] = [];
      let cursor: string | null = null;
      for (let p = 0; p < M; p++) {
        const page = store.loadHistory(CONV, cursor, 1);
        expect(page.envelopes).toHaveLength(1);
        pages.push([...page.envelopes]);
        if (p < M - 1) {
          expect(page.nextCursor, `page ${p + 1}: nextCursor must not be null`).not.toBeNull();
          cursor = page.nextCursor;
        } else {
          // Last page — store exhausted.
          expect(page.nextCursor, "last page: nextCursor must be null").toBeNull();
        }
      }

      // All blobs returned in insertion order.
      const allEnvelopes = pages.flat();
      expect(allEnvelopes).toHaveLength(M);
      for (let i = 0; i < M; i++) {
        expect(allEnvelopes[i]!.messageId).toBe(`msg-${i + 1}`);
      }
    },
  );

  // ── Test 6: pageSize larger than total blobs (single page covers all) ─────

  it(
    "pageSize > M: all M blobs returned in one page; nextCursor null",
    () => {
      const M = 5;
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, M);
      for (const env of envelopes) store.append(CONV, env);

      const page = store.loadHistory(CONV, null, M + 100);
      expect(page.envelopes).toHaveLength(M);
      expect(page.nextCursor).toBeNull();

      for (let i = 0; i < M; i++) {
        expect(page.envelopes[i]!.messageId).toBe(`msg-${i + 1}`);
      }
    },
  );

  // ── Test 7: Empty store — returns empty page and null cursor ─────────────

  it(
    "empty store: load_history returns empty envelopes and null nextCursor",
    () => {
      const store = new HistoryStore();
      const page = store.loadHistory(CONV, null, 10);
      expect(page.envelopes).toHaveLength(0);
      expect(page.nextCursor).toBeNull();
    },
  );

  // ── Test 8: Non-positive limit — returns empty page (defensive) ───────────

  it(
    "limit=0 and limit<0: returns empty page without throwing (defensive contract)",
    () => {
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, 5);
      for (const env of envelopes) store.append(CONV, env);

      const page0 = store.loadHistory(CONV, null, 0);
      expect(page0.envelopes).toHaveLength(0);
      expect(page0.nextCursor).toBeNull();

      const pageNeg = store.loadHistory(CONV, null, -5);
      expect(pageNeg.envelopes).toHaveLength(0);
      expect(pageNeg.nextCursor).toBeNull();
    },
  );

  // ── Test 9: Stale cursor — returns empty page (safe fallback) ────────────

  it(
    "stale/unknown cursor: returns empty page and null cursor (safe fallback)",
    () => {
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, 5);
      for (const env of envelopes) store.append(CONV, env);

      const page = store.loadHistory(CONV, "msg-does-not-exist", 3);
      expect(page.envelopes).toHaveLength(0);
      expect(page.nextCursor).toBeNull();
    },
  );

  // ── Test 10: Cursor pointing to last item — returns empty page ────────────

  it(
    "cursor pointing to the very last blob: returns empty page and null cursor",
    () => {
      const M = 4;
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, M);
      for (const env of envelopes) store.append(CONV, env);

      // Advance cursor to the last item.
      const page = store.loadHistory(CONV, `msg-${M}`, 3);
      expect(page.envelopes).toHaveLength(0);
      expect(page.nextCursor).toBeNull();
    },
  );

  // ── Test 11: Cross-conversation isolation (different sub) ─────────────────

  it(
    "blobs stored for conv-A do not appear in load_history for conv-B (sub isolation)",
    () => {
      const store = new HistoryStore();

      // Populate conv-A (user42) and conv-B (user99).
      const envsA = makeEnvelopes(CONV, 4);
      const envsB = makeEnvelopes(CONV_B, 3);
      for (const env of envsA) store.append(CONV, env);
      for (const env of envsB) store.append(CONV_B, env);

      // conv-A returns only its own blobs.
      const { allEnvelopes: allA } = drainStore(store, CONV, 10);
      expect(allA).toHaveLength(4);
      for (const env of allA) expect(env.sub).toBe(CONV.sub);

      // conv-B returns only its own blobs.
      const { allEnvelopes: allB } = drainStore(store, CONV_B, 10);
      expect(allB).toHaveLength(3);
      for (const env of allB) expect(env.sub).toBe(CONV_B.sub);
    },
  );

  // ── Test 12: Cross-conversation isolation (different accountId) ─────────────

  it(
    "blobs stored for agent1 do not appear in load_history for agent2 (accountId isolation)",
    () => {
      const store = new HistoryStore();

      const envsA = makeEnvelopes(CONV, 3);
      const envsC = makeEnvelopes(CONV_C, 2);
      for (const env of envsA) store.append(CONV, env);
      for (const env of envsC) store.append(CONV_C, env);

      const { allEnvelopes: allA } = drainStore(store, CONV, 10);
      expect(allA).toHaveLength(3);
      for (const env of allA) expect(env.accountId).toBe(CONV.accountId);

      const { allEnvelopes: allC } = drainStore(store, CONV_C, 10);
      expect(allC).toHaveLength(2);
      for (const env of allC) expect(env.accountId).toBe(CONV_C.accountId);
    },
  );

  // ── Test 13: Ciphertext blobs are stored and returned byte-identical ───────

  it(
    "ciphertext envelope content is preserved byte-identical through the store (no mutation)",
    () => {
      const store = new HistoryStore();
      const env = makeOpaqueEnvelope(CONV, "msg-immutable", 1_718_000_100_000);
      store.append(CONV, env);

      const page = store.loadHistory(CONV, null, 1);
      expect(page.envelopes).toHaveLength(1);

      const retrieved = page.envelopes[0]!;
      expect(retrieved.content.nonce).toBe(env.content.nonce);
      expect(retrieved.content.ciphertext).toBe(env.content.ciphertext);
      expect(retrieved.content.tag).toBe(env.content.tag);
      expect(retrieved.v).toBe(1);
      expect(retrieved.messageId).toBe("msg-immutable");
    },
  );

  // ── Test 14: Append after paginated reads — new blobs appear in next call ──

  it(
    "append after pagination: newly appended blobs appear in subsequent load_history calls",
    () => {
      const store = new HistoryStore();
      const envs = makeEnvelopes(CONV, 3);
      for (const env of envs) store.append(CONV, env);

      // Read all 3 blobs.
      const page1 = store.loadHistory(CONV, null, 10);
      expect(page1.envelopes).toHaveLength(3);
      expect(page1.nextCursor).toBeNull();

      // Append 2 more blobs.
      const newEnv1 = makeOpaqueEnvelope(CONV, "msg-new-1", 1_718_000_200_000);
      const newEnv2 = makeOpaqueEnvelope(CONV, "msg-new-2", 1_718_000_201_000);
      store.append(CONV, newEnv1);
      store.append(CONV, newEnv2);

      // Re-read from the beginning — all 5 blobs visible.
      const { allEnvelopes } = drainStore(store, CONV, 10);
      expect(allEnvelopes).toHaveLength(5);
      expect(allEnvelopes[3]!.messageId).toBe("msg-new-1");
      expect(allEnvelopes[4]!.messageId).toBe("msg-new-2");
    },
  );

  // ── Test 15: Mixed envelope types (conversation + history + approval) ──────

  it(
    "stores and returns ciphertext blobs of any envelopeType in insertion order",
    () => {
      const store = new HistoryStore();
      const types: MessageEnvelope["envelopeType"][] = [
        "conversation",
        "approval_request",
        "approval_decision",
        "approval_resolved",
        "history",
        "typing",
      ];

      const envs = types.map((type, i) => ({
        v: 1 as const,
        accountId: CONV.accountId,
        tenant: CONV.tenant,
        sub: CONV.sub,
        messageId: `msg-type-${i + 1}`,
        envelopeType: type,
        ts: 1_718_000_000_000 + i * 1000,
        content: {
          nonce: Buffer.alloc(12, i).toString("base64url"),
          ciphertext: Buffer.from(`type-${type}`).toString("base64url"),
          tag: Buffer.alloc(16, i).toString("base64url"),
        },
      } as MessageEnvelope));

      for (const env of envs) store.append(CONV, env);

      const { allEnvelopes } = drainStore(store, CONV, 3);
      expect(allEnvelopes).toHaveLength(types.length);

      for (let i = 0; i < types.length; i++) {
        expect(allEnvelopes[i]!.envelopeType).toBe(types[i]);
        expect(allEnvelopes[i]!.messageId).toBe(`msg-type-${i + 1}`);
      }
    },
  );

  // ── Test 16: M=1 (single blob) — first and only page ─────────────────────

  it(
    "M=1 single blob: exactly one page with one envelope and nextCursor null",
    () => {
      const store = new HistoryStore();
      const env = makeOpaqueEnvelope(CONV, "msg-only", 1_718_000_000_001);
      store.append(CONV, env);

      const page = store.loadHistory(CONV, null, 5);
      expect(page.envelopes).toHaveLength(1);
      expect(page.envelopes[0]!.messageId).toBe("msg-only");
      expect(page.nextCursor).toBeNull();
    },
  );

  // ── Test 17: Zero-gaps assertion using set comparison ─────────────────────

  it(
    "draining M=10 blobs with pageSize=3: messageId set of returned blobs equals inserted set (zero gaps, no duplicates)",
    () => {
      const M = 10;
      const store = new HistoryStore();
      const envelopes = makeEnvelopes(CONV, M);
      for (const env of envelopes) store.append(CONV, env);

      const { allEnvelopes } = drainStore(store, CONV, 3);

      // Exact count — no duplicates, no gaps.
      expect(allEnvelopes).toHaveLength(M);

      // Set equality — every inserted messageId appears exactly once.
      const insertedIds = new Set(envelopes.map((e) => e.messageId));
      const returnedIds = new Set(allEnvelopes.map((e) => e.messageId));
      expect(returnedIds).toEqual(insertedIds);

      // Ordering — returned sequence matches insertion sequence.
      for (let i = 0; i < M; i++) {
        expect(allEnvelopes[i]!.messageId).toBe(`msg-${i + 1}`);
      }
    },
  );
});

// ---------------------------------------------------------------------------
// Suite 2: size() introspection helper
// ---------------------------------------------------------------------------

describe("HistoryStore.size()", () => {
  it("returns 0 for an empty conversation", () => {
    const store = new HistoryStore();
    expect(store.size(CONV)).toBe(0);
  });

  it("returns the number of appended envelopes", () => {
    const store = new HistoryStore();
    const envelopes = makeEnvelopes(CONV, 5);
    for (let i = 0; i < 5; i++) {
      store.append(CONV, envelopes[i]!);
      expect(store.size(CONV)).toBe(i + 1);
    }
  });

  it("is scoped per conversation — does not count across conversations", () => {
    const store = new HistoryStore();
    const envsA = makeEnvelopes(CONV, 3);
    const envsB = makeEnvelopes(CONV_B, 5);
    for (const e of envsA) store.append(CONV, e);
    for (const e of envsB) store.append(CONV_B, e);
    expect(store.size(CONV)).toBe(3);
    expect(store.size(CONV_B)).toBe(5);
    expect(store.size(CONV_C)).toBe(0); // untouched conversation
  });
});
