/**
 * The key-wrap AAD encoding (agent side) — protocol v3.
 *
 * Deliberately a STANDALONE, dependency-free module (no `node:` imports, only
 * `TextEncoder`/`Uint8Array`): the browser declares its own byte-identical copy in
 * `packages/client/src/e2e-crypto-browser.ts`, and the cross-package parity test
 * (`packages/client/src/wrap-aad-parity.test.ts`) imports THIS file directly to
 * compare the two implementations byte-for-byte. Keeping it free of Node built-ins
 * is what lets that test typecheck under the client's browser-only lib set.
 *
 * Re-exported from `late-join-decryptor.ts`, which is where callers reach it.
 */

/** AAD domain/version prefix. Bumped from the v1 (peerId-only) encoding by v3. */
export const WRAP_AAD_VERSION = "webchannel-wrap-v2" as const;

/**
 * Field delimiter — ASCII 0x1F UNIT SEPARATOR. Written as a numeric constant on
 * purpose: a literal control character in source is invisible and survives
 * copy/paste badly, and this byte must be identical on both sides of the wire.
 */
export const WRAP_AAD_SEPARATOR = 0x1f;

/**
 * F2 + v3 — build the ChaCha20-Poly1305 AAD that binds a wrapped conversation
 * key to exactly ONE peerId AND to exactly ONE register attempt.
 *
 *   UTF-8("webchannel-wrap-v2") ‹0x1F› UTF-8(peerId) ‹0x1F› UTF-8(clientNonce)
 *
 * Two bindings, two distinct attacks:
 *   - `peerId` (F2, anti-LIFT): a wrap minted for peerA cannot be injected into
 *     peerB's register reply — peerB computes `wrapAad(peerB, …)` and Poly1305
 *     fails.
 *   - `clientNonce` (v3, anti-REPLAY): the value is generated by the BROWSER,
 *     freshly per register attempt, so a relay that captured an earlier register
 *     reply cannot make the replayed wrap open under the current attempt's AAD.
 *     A server-issued nonce would NOT work here — see client-nonce.ts.
 *
 * ENCODING. Unambiguous without escaping: `0x1F` cannot occur in either field.
 * `peerId` is constrained to `[A-Za-z0-9_-]{1,128}` by `assertValidSubjectToken`
 * (enforced in nats-register.ts before this is reached) and `clientNonce` to the
 * same base64url alphabet by `isValidClientNonce`. Deliberately NOT
 * `JSON.stringify` — two fixed fields do not justify depending on cross-engine
 * string-escaping behaviour for a byte-exact cross-implementation contract.
 *
 * MUST be byte-identical to the browser's `wrapAad`
 * (packages/client/src/e2e-crypto-browser.ts); `wrap-aad-parity.test.ts` asserts it.
 *
 * DECIDED, NOT OVERLOOKED: `tenant`/`accountId` are deliberately NOT bound here.
 * Reviewed and declined during the v3 work rather than left out. Cross-account
 * separation already rests on per-account `PopChallengeStore` instances and
 * distinct per-account agent identity keys, and since v3 any cross-account wrap
 * replay would additionally need the victim's freshly generated per-attempt
 * `clientNonce`, which an attacker cannot produce. No exploitable path was
 * demonstrated, so this stayed out of the release rather than widening a breaking
 * change for unreachable protection. Re-open it with a concrete attack, not as an
 * apparent oversight. (The same reasoning applies to `popSignedMessage`.)
 */
export function wrapAad(peerId: string, clientNonce: string): Uint8Array {
  const enc = new TextEncoder();
  const version = enc.encode(WRAP_AAD_VERSION);
  const peer = enc.encode(peerId);
  const nonce = enc.encode(clientNonce);
  const out = new Uint8Array(version.length + 1 + peer.length + 1 + nonce.length);
  let at = 0;
  out.set(version, at);
  at += version.length;
  out[at++] = WRAP_AAD_SEPARATOR;
  out.set(peer, at);
  at += peer.length;
  out[at++] = WRAP_AAD_SEPARATOR;
  out.set(nonce, at);
  return out;
}
